#
# From https://notes.depad.fr/2018/0516-minifier-le-contenue-dhugo/
#
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

master:
  stage: build
  script:
    - docker build --pull 
      --build-arg HUGO_VERSION="${HUGO_VERSION}"
      --build-arg MINIFY_VERSION="${MINIFY_VERSION}"
      -t "$CI_REGISTRY_IMAGE" .
    - docker push "${CI_REGISTRY_IMAGE}"
  only:
    - master

tags:
  stage: build
  script:
    - docker build --pull
      --build-arg HUGO_VERSION="${CI_COMMIT_TAG}"
      --build-arg MINIFY_VERSION="${MINIFY_VERSION}"
      -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - master
  only:
    - tags

trigger:
  stage: deploy
  image:
    name: alpine
  before_script:
    - apk add --no-cache curl
  script:
    - "curl -X POST -F token=${CI_NOTE_TOKEN} -F ref=${CI_NOTE_REF} ${CI_NOTE_TRIGGERURL}"